name: cicd

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "container/**"
      - ".github/workflows/cicd.yml"
  # schedule:
  #   #        ┌───────────── minute (0 - 59)
  #   #        │  ┌───────────── hour (0 - 23)
  #   #        │  │ ┌───────────── day of the month (1 - 31)
  #   #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #   #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #   #        │  │ │ │ │
  #   #        │  │ │ │ │
  #   #        │  │ │ │ │
  #   #        *  * * * *
  #   - cron: "15 1 * * 1"

permissions:
  packages: write

concurrency:
  group: cicd
  cancel-in-progress: false

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set datetime
        run: |
          echo "datetime=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
      - name: log in registry.redhat.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REGISTRY_REDHAT_IO_USER }}
          password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}
      - name: build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: antora-viewer
          tags: latest ${{ github.ref_name }}
          context: ./container
          containerfiles: |
            ./Containerfile
          build-args: |
            CREATED_AT=${{ env.datetime }}
            GITHUB_SHA=${{ github.sha }}
      - name: push image to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/juliaaano
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
